name: Python CI/CD Workflow

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3  # Checkout the repository

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"  # Specify the Python version

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov

    - name: Run Tests
      run: |
        pytest --cov=src tests/  # Run tests with coverage report


